### ISSUE TITLE
ERROR in ./packages/geocoder/lib/index.js

### ISSUE THREAD

**Issue by mpaine-act** [opentripplanner/otp-ui#337]
Steps to reproduce:

1) git clone https://github.com/opentripplanner/otp-ui.git
2) cd otp-ui
3) yarn dev

Note this is compiled on Windows 10 (if that matters).

<snip>

WARNING in ./packages/printable-itinerary/node_modules/@opentripplanner/itinerary-body/src/stories/OtpRrItineraryBody.story.js 46:4
Module parse failed: Unexpected token (46:4)
File was processed with these loaders:
 * ./node_modules/@storybook/source-loader/dist/cjs/index.js
You may need an additional loader to handle the result of these loaders.
| }) {
|   return (
>     <ItineraryBodyDefaultsWrapper
|       itinerary={itinerary}
|       LegIcon={ClassicLegIcon}
 @ \.)(?=.)[^\\/]*?\.story\.(js|jsx|ts|tsx))$ (./packages sync ^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.story\.(js|jsx|ts|tsx))$) ./printable-itinerary/node_modules/@opentripplanner/itinerary-body/src/stories/OtpRrItineraryBody.story.js
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yRunner.js-generated-other-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yHighlight.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-other-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/preview.js-generated-other-entry.js ./node_modules/storybook-addon-outline/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined

WARNING in ./packages/printable-itinerary/node_modules/@opentripplanner/itinerary-body/src/stories/OtpUiItineraryBody.story.js 50:4
Module parse failed: Unexpected token (50:4)
File was processed with these loaders:
 * ./node_modules/@storybook/source-loader/dist/cjs/index.js
You may need an additional loader to handle the result of these loaders.
| }) {
|   return (
>     <ItineraryBodyDefaultsWrapper
|       itinerary={itinerary}
|       LegIcon={ClassicLegIcon}
 @ \.)(?=.)[^\\/]*?\.story\.(js|jsx|ts|tsx))$ (./packages sync ^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.story\.(js|jsx|ts|tsx))$) ./printable-itinerary/node_modules/@opentripplanner/itinerary-body/src/stories/OtpUiItineraryBody.story.js
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yRunner.js-generated-other-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yHighlight.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-other-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/preview.js-generated-other-entry.js ./node_modules/storybook-addon-outline/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined

ERROR in ./packages/geocoder/lib/index.js
Module not found: Error: Can't resolve './geocoders/arcgis' in 'P:\github\otp-ui\packages\geocoder\lib'
 @ ./packages/geocoder/lib/index.js 32:37-66
 @ ./packages/core-utils/esm/query.js
 @ ./packages/core-utils/esm/index.js
 @ ./packages/vehicle-rental-overlay/src/VehicleRentalOverlay.story.js
 @ ./packages sync ^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.story\.(js|jsx|ts|tsx))$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yRunner.js-generated-other-entry.js ./node_modules/@storybook/addon-a11y/dist/esm/a11yHighlight.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-other-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/preview.js-generated-other-entry.js ./node_modules/storybook-addon-outline/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.21 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core-common/dist/cjs/templates/index.ejs] 1.96 KiB {HtmlWebpackPlugin_0} [built]
ModuleNotFoundError: Module not found: Error: Can't resolve './geocoders/arcgis' in 'P:\github\otp-ui\packages\geocoder\lib'
    at P:\github\otp-ui\node_modules\webpack\lib\Compilation.js:925:10
    at P:\github\otp-ui\node_modules\webpack\lib\NormalModuleFactory.js:401:22
    at P:\github\otp-ui\node_modules\webpack\lib\NormalModuleFactory.js:130:21
    at P:\github\otp-ui\node_modules\webpack\lib\NormalModuleFactory.js:224:22
    at P:\github\otp-ui\node_modules\neo-async\async.js:2830:7
    at P:\github\otp-ui\node_modules\neo-async\async.js:6877:13
    at P:\github\otp-ui\node_modules\webpack\lib\NormalModuleFactory.js:214:25
    at P:\github\otp-ui\node_modules\enhanced-resolve\lib\Resolver.js:213:14
    at P:\github\otp-ui\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (P:\github\otp-ui\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at P:\github\otp-ui\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7
    at P:\github\otp-ui\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (P:\github\otp-ui\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at P:\github\otp-ui\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (P:\github\otp-ui\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at P:\github\otp-ui\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43
resolve './geocoders/arcgis' in 'P:\github\otp-ui\packages\geocoder\lib'
  using description file: P:\github\otp-ui\packages\geocoder\package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: P:\github\otp-ui\packages\geocoder\package.json (relative path: ./lib/geocoders/arcgis)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        P:\github\otp-ui\packages\geocoder\lib\geocoders\arcgis doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        P:\github\otp-ui\packages\geocoder\lib\geocoders\arcgis.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        P:\github\otp-ui\packages\geocoder\lib\geocoders\arcgis.js doesn't exist
      .jsx
        Field 'browser' doesn't contain a valid alias configuration
        P:\github\otp-ui\packages\geocoder\lib\geocoders\arcgis.jsx doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        P:\github\otp-ui\packages\geocoder\lib\geocoders\arcgis.ts doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        P:\github\otp-ui\packages\geocoder\lib\geocoders\arcgis.tsx doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        P:\github\otp-ui\packages\geocoder\lib\geocoders\arcgis.json doesn't exist
      .cjs
        Field 'browser' doesn't contain a valid alias configuration
        P:\github\otp-ui\packages\geocoder\lib\geocoders\arcgis.cjs doesn't exist
      as directory
        P:\github\otp-ui\packages\geocoder\lib\geocoders\arcgis doesn't exist

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

error Command failed with exit code 1.

**Comment by miles-grant-ibigroup** [comment]
Which version of node are you running?

**Comment by mpaine-act** [comment]
v16.13.1

**Comment by miles-grant-ibigroup** [comment]
Thanks for letting us know about this! We've identified this as a windows-only issue, so would recommend using WSL until we figure out what's going on

**Comment by mpaine-act** [comment]
thank you

**Comment by mcleinman** [comment]
If other people run into this problem, it can be resolved by updating `babel.config.json`.

Change the `env` block from:
```
  "env": {
    "esm": {
      "presets": [["@babel/preset-env", { "modules": false }]]
    }
  },
```

to:
```
  "env": {
    "esm": {
      "presets": [["@babel/preset-env", { "modules": false }]]
    },
    "lib": {
      "presets": [["@babel/preset-env", { "modules": false }]]
    }
  },
```

I'll put up a PR for this as well.

**Comment by mcleinman** [comment]
I've found a fix. This sounds weird, but I just tested and it works with a fresh clone of the project.

In `tsconfig.json`, add a new line under `compilerOptions`: `"allowJs": true,`

Run the project (using `yarn dev`), and you'll get an error:
```
lerna ERR! yarn run tsc exited 1 in '@opentripplanner/core-utils'
lerna ERR! yarn run tsc stdout:
$ tsc
error TS5055: Cannot write file 'C:/Users/cleinmam/code/otp-ui/test-utils/time.js' because it would overwrite input file.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Remove that line that was just added, and run the project again (using `yarn dev`). It should work!

**Comment by mcleinman** [comment]
When using WSL, make sure to be fully in WSL - Clone the repo into the Linux file system, don't have node (running via WSL) run the repo from the Windows file system. Errors will occur when running tests if you have the repo in the Windows file system.

**Comment by grant-humphries** [comment]
The workaround for this is to create the file that can't be found when `yarn dev` is running, so an empty file the below path should allow the install and checks to complete and storybook to launch:

```
<otp-ui-root>/packages/geocoder/lib/geocoders/arcgis.js
```
